swagger: '2.0'
info:
  title: NewsTK API
  description: Useful functions for news analysis in one API.
  version: "1.0.0"
# the domain of the service
host: api.example.com
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
